[package]
name = "microbity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
heapless = "0.7.16"
microbit-v2 = "0.13.0"
panic-halt = "0.2.0"
